= Git Submodule Follies

I wonder what happens when I ...

== Use git submodules

=== Make changes in a submodule

I can change files in a submodule, but the parent project does not see them. I have to change into the submodule on the commandline and commit there.

=== Submodule in Github

Github shows the submodule as a link to a particular commit in another repository. When you dereference that link, it brings you to that exact commit, not to master.

=== Work with Submodules from Idea
Idea allegedly has https://blog.jetbrains.com/idea/2018/09/intellij-idea-2018-3-eap-git-submodules-jvm-profiler-macos-and-linux-and-more/[submodule support as of 2018.3 EAP]. However, I do not see submodule diff or history in Idea 2018.3.5. Only when I go into the submodule folder in the terminal and invoke

    $ git status

from inside the submodule I can see changes I made in the submodule.

=== Clone a repo with submodules

The submodule code is not added automatically, developers need to learn how to pull the code for a submodule.

== Use git subtree

=== Add a submodule

    git subtree add --prefix docker/faas https://github.com/openfaas/faas.git master --squash



